server:
  port: 8090

spring:
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #\u5F00\u542F\u53D1\u9001\u786E\u8BA4\u673A\u5236\uFF0C\u6D88\u606F\u5230\u8FBE\u4EA4\u6362\u673A\u540E\u4F1A\u6709\u56DE\u8C03
    publisher-confirm-type: CORRELATED
    #\u53EF\u4EE5\u786E\u4FDD\u6D88\u606F\u5728\u672A\u88AB\u961F\u5217\u63A5\u6536\u65F6\u8FD4\u56DE
    publisher-returns: true
    listener:
      simple:
        # mq-\u300B\u6D88\u8D39\u8005\u624B\u52A8\u786E\u8BA4
        acknowledge-mode: manual
